from pathlib import Path

from PIL import Image

from cerebrasgemma4.export import (
    embed_asset_images,
    export_filename,
    render_html_document,
    render_pdf_bytes,
)
from cerebrasgemma4.pipeline.jobs import JobStatus, JobStore


def _sample_markdown() -> str:
    return (
        "# Demo Report\n\n"
        "## Summary\n\n"
        "- First point\n\n"
        "![Frame](assets/frame_0001.jpg)\n"
    )


def test_embed_asset_images(tmp_path: Path):
    assets = tmp_path / "assets"
    assets.mkdir()
    img = assets / "frame_0001.jpg"
    Image.new("RGB", (8, 8), color="red").save(img)

    out = embed_asset_images(_sample_markdown(), assets)
    assert "data:image/jpeg;base64," in out
    assert "assets/frame_0001.jpg" not in out


def test_render_html_document(tmp_path: Path):
    assets = tmp_path / "assets"
    assets.mkdir()
    html_doc = render_html_document(_sample_markdown(), assets_dir=assets, title="Demo Report")
    assert "<!DOCTYPE html>" in html_doc
    assert "<h1>Demo Report</h1>" in html_doc
    assert "Generated by Vid2Doc" in html_doc


def test_render_pdf_bytes(tmp_path: Path):
    assets = tmp_path / "assets"
    assets.mkdir()
    html_doc = render_html_document(_sample_markdown(), assets_dir=assets, title="Demo Report")
    pdf = render_pdf_bytes(html_doc)
    assert pdf.startswith(b"%PDF")


def test_export_filename():
    assert export_filename("Hello World!", "abc-123", "pdf").startswith("vid2doc-hello-world-abc-123")


def test_export_endpoints(tmp_path: Path):
    from fastapi.testclient import TestClient

    from cerebrasgemma4.api.main import app

    store = JobStore(root=tmp_path / "jobs")
    record = store.create()
    job_dir = store.path(record.job_id)
    doc_path = job_dir / "document.md"
    doc_path.write_text(_sample_markdown(), encoding="utf-8")
    store.update(
        record.job_id,
        status=JobStatus.COMPLETED,
        document_path=str(doc_path),
        title="Demo Report",
    )

    client = TestClient(app)

    import cerebrasgemma4.api.routes.jobs as jobs_route

    original = jobs_route._get_store
    jobs_route._get_store = lambda: store
    try:
        html_resp = client.get(f"/api/jobs/{record.job_id}/export/html")
        assert html_resp.status_code == 200
        assert "text/html" in html_resp.headers["content-type"]
        assert "Demo Report" in html_resp.text
        assert "attachment" in html_resp.headers.get("content-disposition", "")

        pdf_resp = client.get(f"/api/jobs/{record.job_id}/export/pdf")
        assert pdf_resp.status_code == 200
        assert pdf_resp.content.startswith(b"%PDF")
        assert "application/pdf" in pdf_resp.headers["content-type"]
    finally:
        jobs_route._get_store = original