"""Integration test with mocked Gemma API calls."""

from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from cerebrasgemma4.llm import CompletionResult
from cerebrasgemma4.pipeline.gemma.scout import FrameScore
from cerebrasgemma4.pipeline.jobs import JobStore
from cerebrasgemma4.pipeline.orchestrator import ConvertOptions, run_pipeline


@pytest.fixture
def sample_video(tmp_path: Path) -> Path:
    out = tmp_path / "test.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=3:size=320x240:rate=10",
            "-c:v",
            "libx264",
            "-an",
            str(out),
            "-y",
        ],
        check=True,
    )
    return out


def _mock_scout(*_args, **_kwargs):
    chunk = _args[0]
    scores = [
        FrameScore(
            frame_id=f.frame_id,
            timestamp_sec=f.timestamp_sec,
            relevance=0.9 - i * 0.1,
            brief=f"Frame {f.frame_id}",
            has_readable_text=i == 0,
        )
        for i, f in enumerate(chunk.frames)
    ]
    return scores, {"usage": {}, "time_info": {}}


def _mock_analyze(score, _path, _excerpt, *, asset_name):
    from cerebrasgemma4.pipeline.gemma.analyze import FrameAnalysis

    return (
        FrameAnalysis(
            frame_id=score.frame_id,
            timestamp_sec=score.timestamp_sec,
            title=f"Section {score.timestamp_sec:.0f}s",
            body="Test visual description.",
            quoted_text=["HELLO"],
            asset_name=asset_name,
        ),
        {"usage": {}, "time_info": {}},
    )


def _mock_compose(_data):
    return (
        "# Test Document\n\n## Summary\n\nGenerated by mock pipeline.\n",
        {"usage": {"prompt_tokens": 1, "completion_tokens": 2}, "time_info": {"time_to_first_token": 0.01}},
    )


def test_pipeline_with_mocks(sample_video: Path, tmp_path: Path, monkeypatch):
    monkeypatch.setenv("SIGHTLINE_DEMO_MODE", "0")
    store = JobStore(root=tmp_path / "jobs")
    record = store.create()
    job_id = record.job_id
    video_copy = store.path(job_id) / "source.mp4"
    video_copy.write_bytes(sample_video.read_bytes())

    with (
        patch("cerebrasgemma4.pipeline.orchestrator.get_transcript") as mock_tx,
        patch("cerebrasgemma4.pipeline.gemma.scout_strategy.scout_chunk", side_effect=_mock_scout),
        patch("cerebrasgemma4.pipeline.orchestrator.analyze_frame", side_effect=_mock_analyze),
        patch("cerebrasgemma4.pipeline.orchestrator.compose_complete", side_effect=_mock_compose),
    ):
        from cerebrasgemma4.pipeline.transcript import TranscriptResult

        mock_tx.return_value = TranscriptResult(
            segments=[],
            source="mock",
            full_text="This is a test transcript.",
        )
        doc = run_pipeline(
            store,
            job_id,
            video_copy,
            "test.mp4",
            ConvertOptions(max_frames=2, max_duration_sec=3.0),
        )

    assert doc.exists()
    assert not video_copy.exists()
    text = doc.read_text(encoding="utf-8")
    assert "Test Document" in text
    record = store.load(job_id)
    assert record.status.value == "completed"
    assert record.preview_asset == "preview.jpg"
    assert (store.path(job_id) / "assets" / "preview.jpg").exists()
    assert store.metrics_path(job_id).exists()
    assert record.metrics["scout_calls"] >= 1
    assert "steps" in record.metrics
    assert "cerebras" in record.metrics
    from cerebrasgemma4.pipeline.context import load_context

    ctx = load_context(store.path(job_id))
    assert ctx is not None
    assert ctx.transcript_full_text