"""Export completed reports to standalone HTML and PDF."""

from __future__ import annotations

import base64
import html
import mimetypes
import re
from io import BytesIO
from pathlib import Path

import markdown

_ASSET_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\((assets/[^)]+)\)")

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    body {{
      font-family: Georgia, "Times New Roman", serif;
      max-width: 46rem;
      margin: 2rem auto;
      padding: 0 1.5rem 3rem;
      color: #18181b;
      line-height: 1.65;
      font-size: 11pt;
    }}
    h1 {{
      font-size: 1.65rem;
      margin-top: 0;
      padding-bottom: 0.45rem;
      border-bottom: 2px solid #f97316;
    }}
    h2 {{
      color: #ea580c;
      margin-top: 1.75rem;
      font-size: 1.15rem;
    }}
    h3 {{ font-size: 1rem; margin-top: 1.25rem; }}
    img {{
      display: block;
      max-width: 100%;
      height: auto;
      margin: 0.85rem 0;
      border-radius: 6px;
    }}
    code {{
      font-family: ui-monospace, monospace;
      font-size: 0.9em;
      background: #f4f4f5;
      padding: 0.12rem 0.3rem;
      border-radius: 4px;
    }}
    pre {{
      background: #f4f4f5;
      padding: 0.85rem;
      overflow-x: auto;
      border-radius: 6px;
      font-size: 0.85em;
    }}
    blockquote {{
      margin: 0.75rem 0;
      padding-left: 1rem;
      color: #52525b;
      border-left: 3px solid #f97316;
    }}
    ul, ol {{ padding-left: 1.35rem; }}
    .meta {{
      color: #71717a;
      font-size: 0.82rem;
      margin-bottom: 1.75rem;
    }}
    @media print {{
      body {{ margin: 0; padding: 0.5in; max-width: none; }}
    }}
  </style>
</head>
<body>
  <p class="meta">Generated by Vid2Doc · Gemma 4 on Cerebras</p>
  {body}
</body>
</html>"""


def embed_asset_images(markdown_text: str, assets_dir: Path) -> str:
    """Rewrite assets/ image paths to base64 data URIs for standalone export."""

    def repl(match: re.Match[str]) -> str:
        alt, rel_path = match.group(1), match.group(2)
        asset_path = assets_dir / rel_path.removeprefix("assets/").lstrip("/")
        if not asset_path.exists():
            return match.group(0)
        mime, _ = mimetypes.guess_type(asset_path.name)
        mime = mime or "application/octet-stream"
        encoded = base64.b64encode(asset_path.read_bytes()).decode("ascii")
        return f"![{alt}](data:{mime};base64,{encoded})"

    return _ASSET_IMAGE_RE.sub(repl, markdown_text)


def markdown_to_html_body(markdown_text: str) -> str:
    return markdown.markdown(
        markdown_text,
        extensions=["extra", "sane_lists", "smarty"],
    )


def render_html_document(
    markdown_text: str,
    *,
    assets_dir: Path,
    title: str = "Vid2Doc Report",
) -> str:
    embedded = embed_asset_images(markdown_text, assets_dir)
    body = markdown_to_html_body(embedded)
    return _HTML_TEMPLATE.format(
        title=html.escape(title, quote=True),
        body=body,
    )


def render_pdf_bytes(html_document: str) -> bytes:
    from xhtml2pdf import pisa

    buf = BytesIO()
    result = pisa.CreatePDF(html_document, dest=buf, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF generation failed")
    data = buf.getvalue()
    if not data:
        raise RuntimeError("PDF generation produced empty output")
    return data


def export_filename(title: str | None, job_id: str, ext: str) -> str:
    slug = re.sub(r"[^\w\-]+", "-", (title or "report").lower()).strip("-")
    slug = slug[:48] or "report"
    return f"vid2doc-{slug}-{job_id[:8]}.{ext}"