"""Export completed reports to standalone HTML and PDF."""

from __future__ import annotations

import base64
import html
import mimetypes
import re
from io import BytesIO
from pathlib import Path

import markdown

_ASSET_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\((assets/[^)]+)\)")
_INLINE_MATH_RE = re.compile(r"\$([^\$\n]+?)\$")
_LATEX_SYMBOLS = {
    "\\rightarrow": "→",
    "\\leftarrow": "←",
    "\\Rightarrow": "⇒",
    "\\Leftrightarrow": "⇔",
    "\\leftrightarrow": "↔",
    "\\times": "×",
    "\\cdot": "·",
    "\\leq": "≤",
    "\\geq": "≥",
    "\\neq": "≠",
    "\\infty": "∞",
    "\\pm": "±",
    "\\approx": "≈",
}
_IMG_WITH_CAPTION_RE = re.compile(
    r"<p>\s*<img\s+([^>]*?)alt=\"([^\"]*)\"([^>]*?)/>\s*</p>",
    re.IGNORECASE,
)

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    body {{
      font-family: Georgia, "Times New Roman", serif;
      max-width: 46rem;
      margin: 2rem auto;
      padding: 0 1.5rem 3rem;
      color: #18181b;
      line-height: 1.65;
      font-size: 11pt;
    }}
    h1 {{
      font-size: 1.65rem;
      margin-top: 0;
      padding-bottom: 0.45rem;
      border-bottom: 2px solid #f97316;
    }}
    h2 {{
      color: #ea580c;
      margin-top: 1.75rem;
      font-size: 1.15rem;
    }}
    h3 {{ font-size: 1rem; margin-top: 1.25rem; }}
    figure.doc-figure {{
      margin: 0.85rem 0;
      text-align: center;
    }}
    figure.doc-figure img {{
      display: inline-block;
      max-width: 100%;
      height: auto;
      margin: 0;
      border-radius: 6px;
    }}
    figcaption.doc-figcaption {{
      margin-top: 0.4rem;
      font-size: 0.88rem;
      line-height: 1.4;
      color: #71717a;
      text-align: center;
    }}
    img {{
      display: block;
      max-width: 100%;
      height: auto;
      margin: 0.85rem auto;
      border-radius: 6px;
    }}
    code {{
      font-family: ui-monospace, monospace;
      font-size: 0.9em;
      background: #f4f4f5;
      padding: 0.12rem 0.3rem;
      border-radius: 4px;
    }}
    pre {{
      background: #f4f4f5;
      padding: 0.85rem;
      overflow-x: auto;
      border-radius: 6px;
      font-size: 0.85em;
    }}
    blockquote {{
      margin: 0.75rem 0;
      padding-left: 1rem;
      color: #52525b;
      border-left: 3px solid #f97316;
    }}
    ul, ol {{ padding-left: 1.35rem; }}
    .meta {{
      color: #71717a;
      font-size: 0.82rem;
      margin-bottom: 1.75rem;
    }}
    @media print {{
      body {{ margin: 0; padding: 0.5in; max-width: none; }}
    }}
  </style>
</head>
<body>
  <p class="meta">Generated by FastYoutubeReport · Gemma 4 on Cerebras</p>
  {body}
</body>
</html>"""


def embed_asset_images(markdown_text: str, assets_dir: Path) -> str:
    """Rewrite assets/ image paths to base64 data URIs for standalone export."""

    def repl(match: re.Match[str]) -> str:
        alt, rel_path = match.group(1), match.group(2)
        asset_path = assets_dir / rel_path.removeprefix("assets/").lstrip("/")
        if not asset_path.exists():
            return match.group(0)
        mime, _ = mimetypes.guess_type(asset_path.name)
        mime = mime or "application/octet-stream"
        encoded = base64.b64encode(asset_path.read_bytes()).decode("ascii")
        return f"![{alt}](data:{mime};base64,{encoded})"

    return _ASSET_IMAGE_RE.sub(repl, markdown_text)


def normalize_inline_latex(markdown_text: str) -> str:
    """Convert simple inline LaTeX (e.g. $\\rightarrow$) to Unicode for export."""

    def repl(match: re.Match[str]) -> str:
        body = match.group(1).strip()
        for cmd, char in _LATEX_SYMBOLS.items():
            body = body.replace(cmd, char)
        return body if "\\" not in body else match.group(0)

    return _INLINE_MATH_RE.sub(repl, markdown_text)


def _img_tags_to_figures(html_body: str) -> str:
    """Show markdown image alt text as a centered caption below the image."""

    def repl(match: re.Match[str]) -> str:
        attrs_before, alt, attrs_after = match.group(1), match.group(2), match.group(3)
        cap = (
            f'<figcaption class="doc-figcaption">{html.escape(alt)}</figcaption>'
            if alt
            else ""
        )
        return (
            f'<figure class="doc-figure"><img {attrs_before}alt="{html.escape(alt, quote=True)}"'
            f'{attrs_after}/>{cap}</figure>'
        )

    return _IMG_WITH_CAPTION_RE.sub(repl, html_body)


def markdown_to_html_body(markdown_text: str) -> str:
    body = markdown.markdown(
        normalize_inline_latex(markdown_text),
        extensions=["extra", "sane_lists", "smarty"],
    )
    return _img_tags_to_figures(body)


def render_html_document(
    markdown_text: str,
    *,
    assets_dir: Path,
    title: str = "FastYoutubeReport",
) -> str:
    embedded = embed_asset_images(markdown_text, assets_dir)
    body = markdown_to_html_body(embedded)
    return _HTML_TEMPLATE.format(
        title=html.escape(title, quote=True),
        body=body,
    )


def render_pdf_bytes(html_document: str) -> bytes:
    from xhtml2pdf import pisa

    buf = BytesIO()
    result = pisa.CreatePDF(html_document, dest=buf, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF generation failed")
    data = buf.getvalue()
    if not data:
        raise RuntimeError("PDF generation produced empty output")
    return data


def export_filename(title: str | None, job_id: str, ext: str) -> str:
    slug = re.sub(r"[^\w\-]+", "-", (title or "report").lower()).strip("-")
    slug = slug[:48] or "report"
    return f"fastyoutubereport-{slug}-{job_id[:8]}.{ext}"